name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # main 브랜치에 변화가 생기면 실행

permissions:
  contents: write # gh-pages 브랜치에 쓸 수 있는 권한 부여

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: manual/package-lock.json # 경로 주의

      - name: Install dependencies
        run: |
          cd manual
          npm install

      - name: Build and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cd manual
          npm run deploy
